import type { Metadata } from "next";

import { Manrope } from "next/font/google";
import { GeistMono } from "geist/font/mono";
import DynamicCopilotProvider from "@/components/providers/DynamicCopilotProvider";
import { Nav } from "@/components/ui/nav";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "AG-UI Canvas | CopilotKit with LangGraph Python",
  description: "Generated by CopilotKit with LangGraph Python",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${GeistMono.variable}`}>
      <body className="subpixel-antialiased" suppressHydrationWarning={true}>
        <DynamicCopilotProvider>
          <Nav />
          {children}
        </DynamicCopilotProvider>
      </body>
    </html>
  );
}
